title: "Dr. Tamas Lazar is a 10% Asst. Prof. at Vrije Universiteit Brussel"
description: "Appointments: 10% Asst. Prof at VUB DBIT-SBB and 90% Senior PostDoc at Bio2Byte lab of VUB"
theme: jekyll-theme-cayman
