title: "Dr. Tamas Lazar is a 10% Assistant Professor at Vrije Universiteit Brussel (Belgium)."
description: "Appointments: 10% Assistant Professor at VUB Department of Bioengineering – Structural Biology Brussels and 90% Senior PostDoc at VUB-ULB Interuniversity of Bioinformatics (IB2), Brussels"
theme: jekyll-theme-cayman
